### PR TITLE
feat: Added storybook with button component

### LINKED ISSUE #54: Setup Storybook
## Feature details

- [x] Setup Storybook https://storybook.js.org/
- [x] Add small section in the readme
- [ ] Include at least one component in Storybook
- [x] Johns will publish to https://nndesign.netlify.app/

### PR DESCRIPTION
**Pull request by corn-potage**
This PR adds storybook to the project (along with 2 other default story files included with initialization as reference for now), and a button component based on the current draft specs. Currently only includes 2 icons. Wasn't exactly sure what kind of templates we wanted for stories, but made them based on sizes for now.

@jgresham Do you happen to know what's going on with the typescript errors with the Github Actions? I'm still new with TypeScript, and I looked it up, but it's having issues with the Storybook generated files.. I thought about ignoring these files but that doesn't seem like a good idea either :thinking:

resolves #54

### CODE REVIEW

**Comment by corn-potage** [comment]
> I'll try to add this as part of the `npm run lint` command.

Ahh, I put the folder in .eslintignore temporarily to get the commits in, but I'll remove it from the file and see what the behavior is like after your commit. Thanks for the help!

**Comment by jgresham** [comment]
> > I'll try to add this as part of the `npm run lint` command.
> 
> Ahh, I put the folder in .eslintignore temporarily to get the commits in, but I'll remove it from the file and see what the behavior is like after your commit. Should be ready to merge after that. Thanks for the help!



> > I'll try to add this as part of the `npm run lint` command.
> 
> Ahh, I put the folder in .eslintignore temporarily to get the commits in, but I'll remove it from the file and see what the behavior is like after your commit. Should be ready to merge after that. Thanks for the help!

I'm okay with not linting the stories directory as storybook is mostly for viewing components and visual testing. If linting doesn't cause extra work, I'm ok with enabling it.

**Comment by jgresham** [comment]
Two suggestions (If you could fix first for this PR that'd be ideal):
1. The components shouldn't have references to storybook. The components should work in both the app code and in storybook without any changes to the component. See ExternalLink story as an example. For now we can put redesigned components in `src/renderer/Generics/redesign/...`
2. If there is app level css(scss/sass maybe) code for the redesign (ex. the purple color we will use everywhere), we can put that in a file and import it for all storybook components (ex. here https://github.com/jgresham/nice-node/pull/58/files#diff-98b614e1838b171ee71c04450a8f1a562753193fb7d4f53a4de8b9b5a7e980eeR1)

**Comment by jgresham** [comment]
Great work!! I know config for webpack can be troublesome and hard to debug, so thanks for getting that in here. It's great to see the redesigned button in here too!

The latest commit here is deployed at https://nndesign.netlify.app/

**Pull request merged**
