### PR TITLE
Feature/corn potage/UI redesign

### PR DESCRIPTION
**Pull request by jgresham**

### CODE REVIEW

**Comment by jgresham** [comment]
@corn-potage I think you should work on a new branch, or we can delete this branch and you can create it again off of `ui-redesign`.

The history (already merged work) showing is an unintended consequence of using squash & merge. More here https://stackoverflow.com/questions/49200667/github-squash-and-merge-subsequent-pull-request-showing-all-previous-changes. 

I'm not sure what the best long-term workflow is here. Perhaps, doing a squash on the feature branch (to squash out "fix" or "check-in wip" commits), force pushing to remote, then doing a regular merge might be best.

**Comment by corn-potage** [comment]
Ohhh I didn't even know that we squashed and merged. In that case, based off of your link, would it be ok if we just did a regular merge, and allowed all commit history to show? so I can keep my own redesign branch in parallel with the ui-redesign branch? @jgresham

**Comment by jgresham** [comment]
> Ohhh I didn't even know that we squashed and merged. In that case, based off of your link, would it be ok if we just did a regular merge, and allowed all commit history to show? so I can keep my own redesign branch in parallel with the ui-redesign branch? @jgresham
> 
> edit: I read up more on squash and merge (never really thought too much about regular merge and squash/merge), and I now see how it can be useful.
> 
> I think what you suggested will work. Some potential ways on here? https://stackoverflow.com/questions/25356810/git-how-to-squash-all-commits-on-branch

It should be possible to reset your branch to master after a squash-and-merge and then force push it to Github. Having a somewhat clean & descriptive commit history is helpful for quickly seeing the feature or fix, doesn't need to be perfect.

**Comment by jgresham** [comment]
The cleanest workflow is to squash then force push before merging (ie. squash all "wip", "checkin", "fix" into a single commit which describes the feature or fix.).

**Pull request closed without merging**
